### ISSUE TITLE
Update to Qubes OS 4.0.4

### ISSUE THREAD

**Issue by caschulz88** [Nitrokey/qubes-oem#1]
Hi, might be a simple thing, but I don't have time to test it. There is already Qubes OS 4.0.4 out, so we should update on it for new NitroPad installations by default.

**Comment by daringer** [comment]
Just FYI,
this is already done for NitroPC (inside the `nitropc` branch) and on the way for the Nitropad(s)

**Comment by daringer** [comment]
Confirmed for Nitropads, too... closing
