### ISSUE TITLE
Nitrokey App is not installed

### ISSUE THREAD

**Issue by Niklap97** [Nitrokey/qubes-oem#8]
The Nitrokey App is not included with the installation of Qubes.

**Comment by daringer** [comment]
Adding the nitrokey-app might be a pretty big exercise.

Qubes is using VMs for sandboxing, afaik there is no USB Cube by default (https://www.qubes-os.org/doc/usb-qubes/).
The `nitrokey-app` should be inside such a USB Cube, pre-configuring a USB Cube during OEM-installation would involve creating a template cube (https://www.qubes-os.org/doc/templates/) (maybe during install-time) and making it available from within Qubes ....

**Comment by daringer** [comment]
This being said, the actual work was already there, updated the used template to `fedora-32` so images will just work and provide the `nitrokey-app` inside the fedora template. closing...
